export const MODES = [
  {
    id: 'enhance',
    label: 'Enhance',
    icon: 'sparkles',
    description: 'AI auto-enhance and color correction',
    shortcut: 'E',
  },
  {
    id: 'retouch',
    label: 'Retouch',
    icon: 'wand',
    description: 'Remove blemishes, smooth skin, heal areas',
    shortcut: 'R',
  },
  {
    id: 'background',
    label: 'Background',
    icon: 'layers',
    description: 'Remove, replace, or blur backgrounds',
    shortcut: 'B',
  },
  {
    id: 'upscale',
    label: 'Upscale',
    icon: 'expand',
    description: 'AI super-resolution upscaling',
    shortcut: 'U',
  },
  {
    id: 'generative-fill',
    label: 'Gen Fill',
    icon: 'paintbrush',
    description: 'AI generative fill and inpainting',
    shortcut: 'G',
  },
  {
    id: 'color-grade',
    label: 'Color Grade',
    icon: 'palette',
    description: 'Professional color grading and LUTs',
    shortcut: 'C',
  },
  {
    id: 'denoise',
    label: 'Denoise',
    icon: 'shield',
    description: 'AI noise reduction and sharpening',
    shortcut: 'D',
  },
  {
    id: 'object-remove',
    label: 'Remove Object',
    icon: 'eraser',
    description: 'Select and remove unwanted objects',
    shortcut: 'O',
  },
  {
    id: 'style-transfer',
    label: 'Style Transfer',
    icon: 'image',
    description: 'Apply artistic styles via AI',
    shortcut: 'S',
  },
];
